title: My jupyter tips
theme: minima
author: Jesus Lopez
email: your-email@domain.com
description: > # Tips to speed code in Jupyter"
 In this blog some tips will be post about Jupyter use.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
